// AUTOMATICALLY GENERATED FILE - DO NOT EDIT
// generated by pipeliner@v0.1.0
package main

import (
	"sync"

	"github.com/supershabam/pipeliner"
)

// filenamesToPeople is a generated implementation of the flatMap operator
func filenamesToPeople(ctx pipeliner.Context, concurrency int, in <-chan string, fn func(pipeliner.Context, string) <-chan Person) <-chan Person {
	done := ctx.Done()
	out := make(chan Person)
	go func() {
		defer close(out)
		wg := sync.WaitGroup{}
		wg.Add(concurrency)
		for i := 0; i < concurrency; i++ {
			go func() {
				defer wg.Done()
				for v := range in {
					for w := range fn(ctx, v) {
						select {
						case <-done:
							return
						case out <- w:
						}
					}
				}
			}()
		}
		wg.Wait()
	}()
	return out
}
