// AUTOMATICALLY GENERATED FILE - DO NOT EDIT
// generated by pipeliner@v0.1.0
package main

import "github.com/supershabam/pipeliner"

// fromStrings is a generated implementation of the from operator
func fromStrings(ctx pipeliner.Context, in []string) <-chan string {
	done := ctx.Done()
	out := make(chan string)
	go func() {
		defer close(out)
		for _, v := range in {
			select {
			case <-done:
				return
			case out <- v:
			}
		}
	}()
	return out
}
